site_name: Loca Documentation
site_description: Documentation for the Loca local LLM Streamlit application.
site_author: Terry D. Eppler

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
  palette:
    - scheme: slate
      primary: blue
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            separate_signature: true
            members_order: source
            filters:
              - "!^_"